name: Build and Push Docker Image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.Kingsley1994@}}" | docker login -u "${{ secrets.kobbyprince }}" --password-stdin
      - name: Build and Push Image
        run: |
          docker build -t kobbyprince/node-hello:latest .
          docker push kobbyprince/node-hello:latest
