name: Build and Push Docker Image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Push Image
        run: |
          docker build -t mydockerhubuser/my-node-app:latest .
          docker push mydockerhubuser/my-node-app:latest
